language: java
sudo: false
notifications:
  slack: sem5640-2018:4U7aCLy3FSLaqVepipksnN0a

# Specify which branches can be built on PR merge
branches:
  only:
    - master
    - development

cache:
  directories:
    - $HOME/.m2


install: 
# Build dependencies first so it goes away
- mvn dependency:resolve
script: 
- mvn test -B
